### ISSUE TITLE
incorrect epoch_params on alonzo

### ISSUE THREAD

**Issue by mmahut** [IntersectMBO/cardano-db-sync#782]
We are seeing different value of `min_utxo_value` in epoch parameters table. I know `min_utxo_value` has been decmissioned, but looks like cardano-db-sync kept this name and is filling up the new `utxoCostPerWord` parameter in its place, but only on one host.

`cardano-db-sync 11.0.0 07ee3b0aa3f2991eda0be6c96ec1d6d17e81f732`

**Host 1**
```
csyncdb=> select epoch_no, min_utxo_value, coins_per_utxo_word from epoch_param order by id desc limit 3;
 epoch_no | min_utxo_value | coins_per_utxo_word 
----------+----------------+---------------------
      154 |              0 |                   0
      153 |        1000000 |                    
      152 |        1000000 |                    
(3 rows)

csyncdb=> 
```

**Host 2**
```
csyncdb=> select epoch_no, min_utxo_value, coins_per_utxo_word from epoch_param order by id desc limit 3;
 epoch_no | min_utxo_value | coins_per_utxo_word 
----------+----------------+---------------------
      154 |              0 |                   0
      153 |        1000000 |                    
      152 |        1000000 |                    
(3 rows)

csyncdb=> 
```

**Host 3**
```
csyncdb=> select epoch_no, min_utxo_value, coins_per_utxo_word from epoch_param order by id desc limit 3;
 epoch_no | min_utxo_value | coins_per_utxo_word 
----------+----------------+---------------------
      154 |          34482 |               34482
      153 |        1000000 |                    
      152 |        1000000 |                    
(3 rows)

csyncdb=> 
```

All of these syncs occurred from scratch and not under load, CPU utilization during the sync was around 50%, memory at around 60%. Please, let me know what information to gather to help in debugging.

**Comment by mmahut** [comment]
Also, maybe we should mark `min_utxo_value` as `null` instead of `0`?

**Comment by erikd** [comment]
I think this is fixed by 40130351f1ef8a394dafeedd5188b1fb6ce051c1 . I will test this in the next couple of days.

**Comment by mmahut** [comment]
Sadly, this is still happening on the `1b3c60514011e184b6493b6297843c143cb870f7`.

```
csyncdb=> select epoch_no, min_utxo_value, coins_per_utxo_word from epoch_param order by id desc limit 3;
 epoch_no | min_utxo_value | coins_per_utxo_word 
----------+----------------+---------------------
      290 |              0 |                   0
      289 |        1000000 |                    
      288 |        1000000 |                    
(3 rows)

csyncdb=> 
```

**Comment by mmahut** [comment]
This is still wrong on the current master, apparently not only for min_utxo_value but for other epoch_params as well.

```
csyncdb=> select price_mem, max_tx_ex_mem, max_tx_ex_steps, max_block_ex_mem, max_block_ex_steps, max_val_size, collateral_percent, max_collateral_inputs, coins_per_utxo_word from epoch_param order by epoch_no desc limit 1;
 price_mem | max_tx_ex_mem | max_tx_ex_steps | max_block_ex_mem | max_block_ex_steps | max_val_size | collateral_percent | max_collateral_inputs | coins_per_utxo_word 
-----------+---------------+-----------------+------------------+--------------------+--------------+--------------------+-----------------------+---------------------
         1 |             1 |               1 |                1 |                  1 |         1000 |                100 |                     1 |                   0
(1 row)

```

**Comment by erikd** [comment]
I have only got one instance (nearly synced to chain tip) and I get:
```sql
select epoch_no, min_utxo_value, coins_per_utxo_word from epoch_param order by id desc limit 10 ;
 epoch_no | min_utxo_value | coins_per_utxo_word 
----------+----------------+---------------------
      292 |          34482 |               34482
      291 |          34482 |               34482
      290 |          34482 |               34482
      289 |        1000000 |                    
      288 |        1000000 |                    
      287 |        1000000 |                    
      286 |        1000000 |                    
      285 |        1000000 |                    
      284 |        1000000 |                    
      283 |        1000000 |                    
(10 rows)
```

**Comment by erikd** [comment]
@mmahut Is this issue sorted out? Can this be closed?

**Comment by mmahut** [comment]
Interesting enough. We are seeing it again on `cardano-db-sync-13.2.0.1`:

```
csyncdb=> select epoch_no, min_utxo_value from epoch_param order by id desc limit 5 ;
 epoch_no | min_utxo_value
----------+----------------
      472 |              0
      471 |              0
      470 |           4310
      469 |           4310
      468 |           4310
(5 rows)

csyncdb=>
```
